# Generated by Django 4.0.2 on 2022-06-18 16:52

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_address',
            field=models.EmailField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='neighbour_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text=' Emergency Contacts', max_length=31),
        ),
    ]
