# Generated by Django 4.0.2 on 2022-06-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Business',
        ),
    ]
