# Generated by Django 4.0.2 on 2022-06-19 12:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0002_rename_photo_business'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Neighbourhood',
        ),
    ]
