# Generated by Django 4.0.2 on 2022-06-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_profile_email_address_profile_neighbour_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='neighbour_location',
            new_name='neighbour_name',
        ),
    ]
