# Generated by Django 4.0.2 on 2022-06-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_rename_neighbour_location_profile_neighbour_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='user',
        ),
    ]
